"""
Deep Agents Pattern: Research Assistant with Context Isolation
==============================================================
A main agent that delegates complex research tasks to specialized subagents,
solving the context bloat problem through isolated execution contexts.

Key Concepts:
- Subagents solve context bloat: intermediate tool results stay isolated
- Main agent receives only final summaries, not raw data
- Each subagent has focused tools and clear instructions
- Planning through task delegation, not direct tool orchestration

Deep Agents Features:
- Built-in planning with task/todo tools
- Filesystem backend for persistence
- Subagent delegation via task() tool
- Automatic summarization middleware

This pattern is best when:
- Tasks require many tool calls with large outputs
- You need sustained reasoning across multi-step workflows
- Context management is critical for reliability
- Different phases require specialized expertise

Reference:
- https://docs.langchain.com/oss/python/deepagents/overview
- https://docs.langchain.com/oss/python/deepagents/subagents
- https://github.com/langchain-ai/deepagents
"""

from dotenv import load_dotenv
from deepagents import create_deep_agent

# Load environment variables
load_dotenv()


# ============================================
# Mock Tools for Demo (replace with real implementations)
# ============================================

def web_search(query: str, max_results: int = 5) -> str:
    """Search the web for information.

    Args:
        query: Search query
        max_results: Maximum number of results to return
    """
    # Mock implementation - replace with Tavily, Serper, etc.
    return f"""Search results for "{query}":

1. **LangGraph Documentation** - Official docs covering multi-agent patterns
   URL: https://docs.langchain.com/langgraph
   Summary: Comprehensive guide to building agentic workflows with LangGraph.

2. **Multi-Agent Architectures Blog** - Deep dive into agent coordination
   URL: https://blog.langchain.com/multi-agent
   Summary: Comparison of supervisor, swarm, and hierarchical team patterns.

3. **Deep Agents Repository** - Open-source framework for complex agents
   URL: https://github.com/langchain-ai/deepagents
   Summary: Planning, filesystem, and subagent delegation capabilities.

4. **Academic Paper: Agent Coordination** - Research on multi-agent systems
   Summary: Analysis of context management strategies in LLM agents.

5. **Tutorial: Building Research Agents** - Step-by-step implementation guide
   Summary: Practical walkthrough of research agent architecture."""


def analyze_data(data: str, analysis_type: str = "summary") -> str:
    """Analyze data and extract insights.

    Args:
        data: Raw data to analyze
        analysis_type: Type of analysis (summary, trends, comparison)
    """
    return f"""Analysis Results ({analysis_type}):

Key Findings:
- Multi-agent systems outperform single agents on complex tasks by 30-90%
- Context isolation is critical for maintaining agent reliability
- Subagent patterns reduce context bloat by keeping intermediate results isolated
- Clear task boundaries improve delegation accuracy

Trends Identified:
1. Increasing adoption of hierarchical agent architectures
2. Shift from monolithic to modular agent designs
3. Growing emphasis on context management strategies

Recommendations:
- Use subagents for tasks with large intermediate outputs
- Keep main agent focused on coordination, not execution
- Implement summarization at subagent boundaries"""


def write_report(title: str, sections: str, format: str = "markdown") -> str:
    """Write a structured report.

    Args:
        title: Report title
        sections: Content sections as JSON or structured text
        format: Output format (markdown, html, plain)
    """
    return f"""# {title}

## Executive Summary
This report synthesizes research findings on the specified topic, providing
actionable insights and recommendations based on comprehensive analysis.

## Key Findings
{sections}

## Methodology
- Web research across multiple authoritative sources
- Data analysis using structured extraction techniques
- Synthesis through multi-agent coordination

## Conclusions
The research demonstrates clear patterns and provides a foundation for
informed decision-making on the topic.

---
*Report generated by Deep Agents Research Assistant*"""


# ============================================
# Subagent Definitions
# ============================================

# Research subagent: Handles web searches and information gathering
research_subagent = {
    "name": "researcher",
    "description": "Conducts web research to gather information on topics. "
                   "Use this for finding facts, statistics, and source material. "
                   "Returns concise summaries with source citations.",
    "system_prompt": """You are an expert researcher. Your job is to:
1. Break down research questions into specific search queries
2. Use web_search to find relevant, authoritative information
3. Synthesize findings into a concise summary
4. Always cite sources with URLs when making claims

Output format:
- Summary (2-3 paragraphs max)
- Key facts (bullet points)
- Sources (with URLs)

IMPORTANT: Keep your response under 500 words. Exclude raw search results
and intermediate reasoning from your final output.""",
    "tools": [web_search],
}

# Analysis subagent: Processes and analyzes collected data
analysis_subagent = {
    "name": "analyst",
    "description": "Analyzes data and research findings to extract insights, "
                   "identify trends, and provide recommendations. "
                   "Use this after gathering raw information.",
    "system_prompt": """You are a data analyst specializing in synthesis and insight extraction.

Your job is to:
1. Receive raw data or research findings
2. Identify patterns, trends, and key insights
3. Provide actionable recommendations
4. Quantify findings when possible

Output format:
- Key Insights (3-5 bullet points)
- Trends (numbered list)
- Recommendations (prioritized)
- Confidence level (high/medium/low)

IMPORTANT: Focus on actionable insights. Keep response under 400 words.
Do not include raw data in your output.""",
    "tools": [analyze_data],
}

# Writer subagent: Produces polished final reports
writer_subagent = {
    "name": "writer",
    "description": "Writes polished, professional reports and documents. "
                   "Use this to produce final deliverables from research and analysis.",
    "system_prompt": """You are a professional technical writer.

Your job is to:
1. Take research findings and analysis
2. Structure content logically
3. Write clear, concise prose
4. Format for readability

Output requirements:
- Use markdown formatting
- Include executive summary
- Organize with clear headings
- Keep total length under 800 words

IMPORTANT: Focus on clarity and actionability. The reader should understand
key points within 2 minutes of reading.""",
    "tools": [write_report],
}


# ============================================
# Main Agent Configuration
# ============================================

MAIN_AGENT_PROMPT = """You are a research coordinator managing a team of specialists.

Your team:
- **researcher**: Gathers information from web searches
- **analyst**: Analyzes data and extracts insights
- **writer**: Produces polished final reports

Your workflow:
1. Break down user requests into research, analysis, and writing phases
2. Delegate to appropriate subagents using the task() tool
3. Coordinate results to fulfill the user's request
4. Provide a final summary to the user

IMPORTANT:
- Always delegate specialized work to subagents
- Do NOT try to do research, analysis, or writing yourself
- Your role is coordination and synthesis
- Keep your responses focused on what the user asked for

When delegating, be specific:
- task(name="researcher", task="Research [specific topic]")
- task(name="analyst", task="Analyze [specific data/findings]")
- task(name="writer", task="Write report on [topic] covering [sections]")
"""


# ============================================
# Create Deep Agent
# ============================================

def create_research_assistant():
    """Create a Deep Agent research assistant with specialized subagents."""
    agent = create_deep_agent(
        model="openai:gpt-4o-mini",  # Use OpenAI model
        system_prompt=MAIN_AGENT_PROMPT,
        subagents=[research_subagent, analysis_subagent, writer_subagent],
        name="research-coordinator",
    )
    return agent


# ============================================
# Example Usage
# ============================================

if __name__ == "__main__":
    print("=" * 60)
    print("DEEP AGENTS PATTERN: Research Assistant")
    print("=" * 60)
    print("\nArchitecture:")
    print("  Main Agent (Coordinator)")
    print("    ├── researcher (web search, information gathering)")
    print("    ├── analyst (data analysis, insight extraction)")
    print("    └── writer (report generation)")
    print("\nKey Feature: Context Isolation")
    print("  - Subagents handle tool-heavy work in isolated contexts")
    print("  - Main agent receives only final summaries")
    print("  - Prevents context bloat from intermediate results")
    print("=" * 60)

    # Create the agent
    agent = create_research_assistant()

    # Example queries demonstrating subagent delegation
    queries = [
        # Simple research task
        "What are the main multi-agent patterns in LangChain?",

        # Complex task requiring multiple subagents
        "Research the current state of AI agent architectures, analyze the trends, "
        "and write a brief report with recommendations for building production agents.",
    ]

    for i, query in enumerate(queries, 1):
        print(f"\n{'='*60}")
        print(f"Query {i}: {query}")
        print("-" * 60)

        result = agent.invoke({
            "messages": [{"role": "user", "content": query}]
        })

        # Extract final response
        final_message = result["messages"][-1]
        print(f"\nResponse:\n{final_message.content}")

    print("\n" + "=" * 60)
    print("Deep Agents Benefits Demonstrated:")
    print("  1. Context isolation - subagent tool calls don't bloat main context")
    print("  2. Specialized expertise - each subagent has focused instructions")
    print("  3. Modular architecture - easy to add/modify subagents")
    print("  4. Clear delegation - main agent coordinates, doesn't execute")
    print("=" * 60)
